baseURL = "https://example.com"
title = "Tofa"
author = "chick-p"
copyright = "Copyright © 2020, chick-p and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "ja"
DefaultContentLanguage = "ja"
themesDir = "../.."
theme = "hugo-theme-tofa"

hasCJKLanguage = true
summaryLength = 50

pygmentscodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsoptions = "linenos=inline"

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

enableEmoji = true

[Params]
  description = "This is a HUGO theme."
  defaultEmoji = ":custard:"

[Params.author]
  name = "chick-p"
  description = "This is author description"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  archive = "archives"

[Params.social]
  twitter = "_chick_p"
  github = "chick-p"

[outputFormats.rss]
  baseName = "atom"
